// <auto-generated />
using DiscordBot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DiscordBot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701120000_AddCommandPanelAndTicketCleanup")]
    partial class AddCommandPanelAndTicketCleanup
    {
    }
}
