export interface ActivityGame { id: string; gameVersionId?: string | null; version?: string | null; status?: string | null; key: string; name: string; description?: string; iconUrl?: string; activityRoute: string; frontendUrl?: string | null; backendUrl?: string | null; engineType: 'Platform' | 'External' | 'Hybrid' | string; frontendMode: 'InternalRoute' | 'ExternalUrl' | 'Iframe' | string; manifestJson?: string | null; playMode: 'Solo' | 'Multiplayer'; supportsScores: boolean; supportsLeaderboard: boolean; isSandbox: boolean; sandboxWarning?: string | null; }
export interface LeaderboardEntry { rank: number; userDiscordId: string; username: string; totalPoints: number; gamesPlayed: number; wins: number; losses: number; currentStreak: number; bestStreak: number; }
export interface ActivityContext { guildDiscordId: string; channelDiscordId: string; gamesChannelDiscordId: string; games: ActivityGame[]; leaderboard: LeaderboardEntry[]; }
export interface StartSessionResponse { sessionId: string; gameKey: string; gameName: string; activityRoute: string; expiresAt: string; }
export interface CompleteSessionResponse { sessionId: string; pointsAwarded: number; player: LeaderboardEntry; }
export interface ActivityIdentity { accessToken: string; activitiesAccessToken?: string | null; activitiesTokenExpiresAt?: string | null; activityInstanceId?: string | null; userId: string; username: string; avatarUrl?: string | null; guildId: string; channelId: string; }
export interface GameWallet { balance: number; }
export interface PowerUpStoreItem { key: string; name: string; description: string; icon: string; isEnabledForGuild: boolean; price: number; maxUsesPerGame: number; ownedQuantity: number; }
export interface PowerUpStore { balance: number; items: PowerUpStoreItem[]; }
export interface PurchasePowerUpResponse { balance: number; powerUpKey: string; ownedQuantity: number; }
export interface RoulettePlayer { userDiscordId: string; username: string; displayName: string; avatarUrl?: string | null; isHost: boolean; isAlive: boolean; position: number; eliminations: number; joinedAt: string; eliminatedAt?: string | null; }
export interface RouletteAction { roundNumber: number; actionType: string; actorUserDiscordId: string; targetUserDiscordId?: string | null; message: string; powerUpKey?: string | null; powerUpName?: string | null; powerUpIcon?: string | null; createdAt: string; }
export interface RouletteSpinInfo { spinnerUserDiscordId: string; spinnerUsername: string; spinnerAvatarUrl?: string | null; targetUserDiscordId: string; targetUsername: string; targetAvatarUrl?: string | null; selectedIndex: number; resultType: string; createdAt: string; }
export interface RouletteRoom { id: string; gameSessionId: string; activitySessionId: string; guildDiscordId: string; channelDiscordId: string; hostUserDiscordId: string; hostUsername: string; status: 'Waiting' | 'InProgress' | 'Completed' | 'Cancelled' | 'Expired' | 'Abandoned'; minPlayers: number; maxPlayers: number; winnerCoins: number; secondPlaceCoins: number; participationCoins: number; currentRound: number; expiresAt: string; startedAt?: string | null; completedAt?: string | null; canStart: boolean; isCurrentUserJoined: boolean; currentTurnUserDiscordId?: string | null; currentTurnUsername?: string | null; currentTurnPlayer?: RoulettePlayer | null; pendingTargetUserDiscordId?: string | null; pendingTargetUsername?: string | null; pendingTargetPlayer?: RoulettePlayer | null; pendingActionStatus: 'None' | 'WaitingForPowerUp' | 'AutoResolved' | 'Resolved' | string; pendingActionExpiresAt?: string | null; lastSpinResult?: RouletteSpinInfo | null; actions: RouletteAction[]; players: RoulettePlayer[]; alivePlayers: RoulettePlayer[]; eliminatedPlayers: RoulettePlayer[]; winner?: RoulettePlayer | null; }
export interface RouletteSpinResult { room: RouletteRoom; eliminatedPlayer?: RoulettePlayer | null; targetPlayer?: RoulettePlayer | null; alivePlayers: RoulettePlayer[]; selectedIndex: number; targetHasUsablePowerUps: boolean; usablePowerUps: PowerUpStoreItem[]; }
export interface PendingRouletteIntent { roomId: string; }
export interface MyActiveRouletteRoom { hasRoom: boolean; roomId?: string | null; status?: 'Waiting' | 'InProgress' | 'Abandoned' | string | null; isHost: boolean; resumeAllowed?: boolean; resumeReason?: string | null; }
export interface RouletteRuntimeCapabilities { runtimeVersion: string; supportsWalletBets: boolean; supportsPowerUps: boolean; supportsReconnect: boolean; }
