import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { getRouletteRoom, getStore, joinRouletteRoom, leaveRouletteRoom, resolveRoulettePendingAction, spinRoulette, startRouletteRoom, useRoulettePowerUp } from '../lib/api';
import { useActivity } from '../context/ActivityProvider';
import type { PowerUpStoreItem, RouletteRoom } from '../types';
import './RoulettePage.css';

const statusText: Record<string, string> = { Waiting: 'بانتظار اللاعبين', InProgress: 'اللعبة جارية', Completed: 'اكتملت اللعبة', Cancelled: 'أُلغيت الغرفة', Expired: 'انتهت مدة الانضمام' };

export function RouletteRoomPage() {
  const { roomId = '' } = useParams(); const { identity } = useActivity(); const navigate = useNavigate();
  const [room, setRoom] = useState<RouletteRoom | null>(null); const [inventory, setInventory] = useState<PowerUpStoreItem[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [event, setEvent] = useState(''); const [now, setNow] = useState(Date.now()); const [spinning, setSpinning] = useState(false);
  const resolvingRef = useRef(false);
  const load = async () => { if (!identity || !roomId) return; try { const value = await getRouletteRoom(identity.accessToken, roomId, identity.guildId, identity.channelId); setRoom(value); if (value.status === 'InProgress') { const store = await getStore(identity.accessToken, identity.guildId); setInventory(store.items); } } catch (e) { setError(e instanceof Error ? e.message : 'تعذر تحميل الغرفة.'); } };
  useEffect(() => { void load(); }, [identity, roomId]);
  useEffect(() => { const id = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(id); }, []);
  useEffect(() => { if (!room || !['Waiting', 'InProgress'].includes(room.status)) return; const id = window.setInterval(() => void load(), 2500); return () => window.clearInterval(id); }, [room?.status, identity, roomId]);
  const me = useMemo(() => room?.players.find(x => x.userDiscordId === identity?.userId), [room, identity]); const isHost = room?.hostUserDiscordId === identity?.userId;
  const isMyTurn = room?.currentTurnUserDiscordId === identity?.userId; const isPendingTarget = room?.pendingTargetUserDiscordId === identity?.userId && room?.pendingActionStatus === 'WaitingForPowerUp';
  const joinSeconds = room ? Math.max(0, Math.ceil((new Date(room.expiresAt).getTime() - now) / 1000)) : 0;
  const pendingSeconds = room?.pendingActionExpiresAt ? Math.max(0, Math.ceil((new Date(room.pendingActionExpiresAt).getTime() - now) / 1000)) : 0;
  useEffect(() => { if (!identity || !room || room.pendingActionStatus !== 'WaitingForPowerUp' || pendingSeconds > 0 || resolvingRef.current) return; resolvingRef.current = true; resolveRoulettePendingAction(identity.accessToken, room.id, identity.guildId, identity.channelId).then(setRoom).catch(() => undefined).finally(() => { resolvingRef.current = false; }); }, [pendingSeconds, room?.pendingActionStatus, room?.id, identity]);
  const act = async (fn: () => Promise<RouletteRoom>, success = '') => { if (busy) return; setBusy(true); setError(''); try { const value = await fn(); setRoom(value); setEvent(success); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر إكمال الطلب.'); } finally { setBusy(false); } };
  const leave = async () => { if (busy || !identity) return; setBusy(true); setError(''); try { await leaveRouletteRoom(identity.accessToken, roomId, identity.guildId, identity.channelId); navigate('/games/roulette', { replace: true }); } catch (e) { setError(e instanceof Error ? e.message : 'تعذر مغادرة الغرفة.'); setBusy(false); } };
  const spin = async () => { if (!identity || busy) return; setBusy(true); setSpinning(true); setError(''); try { const value = await spinRoulette(identity.accessToken, roomId, identity.guildId, identity.channelId); setTimeout(() => { setRoom(value.room); setEvent(value.targetPlayer ? `العجلة اختارت ${value.targetPlayer.username}` : 'تم تدوير العجلة.'); setSpinning(false); setBusy(false); }, 2800); } catch (e) { setSpinning(false); setBusy(false); setError(e instanceof Error ? e.message : 'تعذر تدوير الروليت.'); } };
  const usePower = async (key: string) => { if (!identity || busy) return; await act(() => useRoulettePowerUp(identity.accessToken, roomId, identity.guildId, identity.channelId, key), 'تم استخدام الخاصية.'); void load(); };
  if (!room || !identity) return <main className="center-state"><div className="loader"/><p>{error || 'جاري تحميل غرفة الروليت...'}</p></main>;
  const alive = room.players.filter(x => x.isAlive); const usable = inventory.filter(x => x.isEnabledForGuild && x.ownedQuantity > 0);
  return <main className="page compact"><div className="roulette-room-head"><button className="text-button" onClick={() => navigate('/games/roulette')}>← الروليت</button><span className={`status-pill status-${room.status.toLowerCase()}`}>{statusText[room.status]}</span></div>
    <section className="roulette-stage"><div className={`roulette-wheel animated-wheel ${spinning ? 'spinning' : ''}`}>{alive.map((player, index) => <span key={player.userDiscordId} style={{ transform: `rotate(${(360 / Math.max(alive.length, 1)) * index}deg) translateY(-5.8rem) rotate(-${(360 / Math.max(alive.length, 1)) * index}deg)` }}>{player.username.slice(0, 10)}</span>)}<b>🎡</b></div><h1>{room.status === 'Completed' ? `🏆 الفائز: ${room.winner?.username}` : `الجولة ${room.currentRound || 0}`}</h1>{room.status === 'Completed' ? <p>حصل على {room.winnerCoins} عملة</p> : room.status === 'Waiting' ? <p>متبقي للانضمام: {joinSeconds} ثانية</p> : room.pendingActionStatus === 'WaitingForPowerUp' ? <p>العجلة اختارت <b>{room.pendingTargetUsername}</b> · متبقي {pendingSeconds} ثانية لاستخدام خاصية</p> : <p>الدور الآن: <b>{room.currentTurnUsername ?? 'غير محدد'}</b></p>}{event && <div className="event-banner">{event}</div>}</section>
    {error && <p className="error-text">{error}</p>}
    {isPendingTarget && <section className="players-card powerup-panel"><div><h2>أنت مستهدف الآن</h2><p className="muted">استخدم خاصية قبل انتهاء العدّاد، أو انتظر وسيتم تنفيذ الإقصاء.</p></div><div className="powerup-actions">{usable.length === 0 ? <button className="button secondary" onClick={() => navigate('/store')}>اذهب للمتجر</button> : usable.map(item => <button className="button secondary" disabled={busy} onClick={() => void usePower(item.key)} key={item.key}>{item.icon} {item.name} ({item.ownedQuantity})</button>)}</div></section>}
    <section className="players-card"><div className="room-meta"><span>اللاعبون <b>{room.players.length}/{room.maxPlayers}</b></span><span>الحيّون <b>{alive.length}</b></span></div><div className="player-list">{room.players.map(player => <div className={`player-chip ${player.isAlive ? '' : 'eliminated'} ${player.userDiscordId === room.currentTurnUserDiscordId ? 'current' : ''} ${player.userDiscordId === room.pendingTargetUserDiscordId ? 'pending' : ''}`} key={player.userDiscordId}><span>{player.isAlive ? '🙂' : '💥'} {player.username}</span>{player.isHost && <small>المضيف</small>}{player.userDiscordId === room.currentTurnUserDiscordId && <small>الدور</small>}{player.userDiscordId === room.pendingTargetUserDiscordId && <small>مستهدف</small>}</div>)}</div></section>
    <div className="button-row">{!me && room.status === 'Waiting' && <button className="button primary" disabled={busy} onClick={() => void act(() => joinRouletteRoom(identity.accessToken, roomId, identity.guildId, identity.channelId), 'تم الانضمام للجولة')}>انضمام</button>}{isHost && room.status === 'Waiting' && <button className="button primary" disabled={busy || !room.canStart} onClick={() => void act(() => startRouletteRoom(identity.accessToken, roomId, identity.guildId, identity.channelId), 'بدأت اللعبة!')}>بدء اللعبة</button>}{room.status === 'InProgress' && <button className="button danger" disabled={busy || !isMyTurn || room.pendingActionStatus === 'WaitingForPowerUp'} onClick={() => void spin()}>{spinning ? 'العجلة تدور...' : isMyTurn ? 'تدوير الروليت' : 'ليس دورك الآن'}</button>}<button className="button secondary" onClick={() => navigate('/store')}>المتجر</button>{me && room.status === 'Waiting' && <button className="button secondary" disabled={busy} onClick={() => void leave()}>مغادرة الغرفة</button>}{room.status === 'Completed' && <><button className="button primary" onClick={() => navigate('/games')}>العودة لمركز الألعاب</button><button className="button secondary" onClick={() => navigate('/leaderboard')}>عرض الترتيب</button></>}</div>
    <section className="players-card action-log"><h2>سجل الجولة</h2>{room.actions.length === 0 ? <p className="muted">لا توجد أحداث بعد.</p> : room.actions.map(action => <p key={`${action.createdAt}-${action.actionType}`}>{action.message}</p>)}</section>
  </main>;
}
